# Generated by Django 5.2 on 2025-04-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('specialization', models.TextField(max_length=250)),
                ('years_of_experience', models.IntegerField()),
                ('hospital_affiliation', models.TextField(max_length=250)),
            ],
        ),
    ]
