# Generated by Django 5.2 on 2025-05-06 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_prescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='prescription',
        ),
    ]
